name: Post merge queue CI

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
        - main

# Define the jobs
jobs:
  decode-base64:
    runs-on: ubuntu-latest

    outputs:
      skip_ci: ${{ steps.output.outputs.skip_ci }}
      origin: ${{ steps.output.outputs.origin }}

    steps:
      # Step 1: Extract the commit message
      - name: Get commit message
        id: get_commit_message
        run: |
          commit_message="${{ github.event.commits[0].message }}"
          echo "Commit message: $commit_message"
          echo "BASE64_STRING=$commit_message" >> $GITHUB_ENV

      # Step 2: Decode the Base64 string and save as JSON
      - name: Decode Base64 string
        run: |
          decoded_json=$(echo "$BASE64_STRING" | base64 --decode)
          echo "Decoded JSON: $decoded_json"
          echo "$decoded_json" > decoded.json

      # Step 3: Parse JSON and set as environment variables
      - name: Set environment variables from JSON
        run: |
          for key in $(jq -r 'keys[]' decoded.json); do
            value=$(jq -r ".\"$key\"" decoded.json)
            echo "$key=$value" >> $GITHUB_ENV
          done

      # Step 4: Use environment variables in subsequent steps
      - name: Print environment variables
        id: output
        run: |
          echo "Decoded key1: ${{env.origin}}"
          echo "Decoded key2: ${{env.skip_ci}}"
          echo "::set-output name=origin::${{env.origin}}"
          echo "::set-output name=skip_ci::${{env.skip_ci}}"

         
  condtional-job-1:
    needs: decode-base64
    runs-on: ubuntu-latest
    if: needs.decode-base64.outputs.skip_ci != 'true'

    steps:
      - name: Run conditional job step
        run: echo "Running because skip is not true."

  condtional-job-2:
    needs: decode-base64
    runs-on: ubuntu-latest
    if: needs.decode-base64.outputs.skip_ci == 'true' && needs.decode-base64.outputs.origin == 'renaming_webhook'

    steps:
      - name: Run conditional job step
        run: echo "Running because skip is true and origin is true"
            
    
    